# {{cookiecutter.project_slug}}/configs/params.yaml
# Example configuration file

data:
  raw_path: data/raw/
  processed_path: data/processed/
  # Add other data-related parameters

features:
  # Feature engineering parameters
  n_features: 10

model:
  # Model training parameters (example for scikit-learn)
  type: RandomForestClassifier
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

# Add other sections as needed (e.g., api, evaluation)
